spring.datasource:
  url: jdbc:postgresql://localhost:5432/identity
  platform: postgres
  username: identity
  password: identity
  driverClassName: org.postgresql.Driver

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL94Dialect

#spring.session:
#  store-type: jdbc
#  jdbc:
#    initialize-schema: always
#    schema: classpath:db/session_store.sql
#    table-name: SPRING_SESSION

#  redis:
#    host: localhost
#    port: 6379
