server.port: 8080

---

spring.profiles: jdbc

spring.datasource:
  url: jdbc:postgresql://localhost:5432/identity
  platform: postgres
  username: identity
  password: identity

spring.jpa.properties.hibernate:
  dialect: org.hibernate.dialect.PostgreSQL94Dialect
  # disable hibrenate warning ons startup
  temp.use_jdbc_metadata_defaults: false

liquibase.change-log: classpath:db/changelog/db.changelog-master.xml

spring.session:
  store-type: jdbc
  jdbc:
    # table spring_session should be created manually
    # script folder: org/springframework/session/jdbc
    initialize-schema: never # DOES THIS EVEN WORKING ???

---

spring.profiles: redis

spring:
  session.store-type: redis
  redis:
    host: localhost
    port: 6379
